## Basic Configuration

baseURL = "https://graphwiz.ai/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "GraphWiz"
title = "GraphWiz"

theme = "tobi-goa"

## Hugo Built-in Features
disqusShortname = "https-tobiasweede-github-io"
googleAnalytics = "XYZ"
enableRobotsTXT = true

## allow raw HTML
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

## Site Settings
[params]
author = "GraphWiz"
intro = "ğŸŒ / AI ğŸ¤– / DevOps ğŸ› ï¸ / Digital Sovereignty ğŸ” / XR ğŸ•¶ï¸"
description = "Transforming complex technology into solutions for ğŸš€ efficiency, ğŸŒ market reach, and ğŸ’° sustainable revenue."
authorimage = "graphwiz_big.png"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "AI & XR enthusiasm"
keywords = "ai,xr,ar,vr"

## Social Accounts
[params.social]

linkedin = "company/graphwiz-ai-cloud-xr"
email = "info@graphwiz.ai"

## Extras
[params.extra]
copyright = "Â© 2025. GraphWiz. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = false
hightlightjs = true

## Main Menu
[[menu.main]]
    name = "Focus Areas"
    identifier = "focus-areas"
    weight = 50
    url = "/focus-areas/"
[[menu.main]]
    name = "Artificial Intelligence"
    identifier = "ai"
    weight = 100
    url = "/ai/"
[[menu.main]]
    name = "eXtended Reality"
    weight = 200
    identifier = "xr"
    url = "/xr/"
[[menu.main]]
    name = "Digital Sovereignty"
    weight = 250
    identifier = "digital-sovereignty"
    url = "/digital-sovereignty/"
[[menu.main]]
    name = "Operations"
    weight = 300
    identifier = "ops"
    url = "/ops"
[[menu.main]]
    name = "Security"
    weight = 350
    identifier = "security"
    url = "/security"
[[menu.main]]
    name = "Workshops"
    weight = 400
    identifier = "Workshops"
    url = "/workshops"
