## Basic Configuration

baseURL = "https://next.tobias-weiss.org/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Tobias Weiss"
title = "Tobias Weiss"

theme = "tobi-goa"

## Hugo Built-in Features
disqusShortname = "https-tobias-weiss-ai-xr-github-io"
googleAnalytics = "XYZ"
enableRobotsTXT = true

## allow raw HTML
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

## Site Settings
[params]
author = "Tobias Weiss"
intro = ""
description = ""
authorimage = "me_wanted_big.png"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Personal homepage"
keywords = "ai,it,guitar,biking,jogging,hugo,xr,ar,vr"

## Social Accounts
[params.social]
github = "tobias-weiss-ai-xr"
email = "spam@tobias-weiss.org"
linkedin = "in/tobias-weiss-ai-xr"

## Extras
[params.extra]
copyright = "Â© 2025. Tobias Weiss. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = false
hightlightjs = true

## Main Menu
[[menu.main]]
    name = "graphwiz"
    identifier = "graphwiz"
    weight = 150
    url = "/graphwiz/"
[[menu.main]]
    name = "research"
    identifier = "research"
    weight = 200
    url = "/research/"
[[menu.main]]
    name = "photo gallery"
    identifier = "gallery"
    weight = 300
    url = "/gallery/"
[[menu.main]]
    name = "pretty good privacy"
    weight = 400
    identifier = "pgp"
    url = "/pgp/"
